Finished Login command handler and validators.
zgorcsos/springtech-atodoc-connector pull request #6
Opened 2024-09-15 15:54 UTC by ggeryx

2024-09-15 16:04 UTC, zgorcsos requested changes

2024-09-15 16:04 UTC, zgorcsos commented on src/Core/AutodocConnector.Application/Features/AutodocRestApi/AutodocLogin/AutodocLoginCommandHandler.cs
> +            var user = await userRepository.GetUserByLoginCredentialsAsync(request.UserName,request.Password);
be AutodocLoginAsync instead GetUserByLoginCredentialsAsync

2024-09-15 16:04 UTC, zgorcsos commented on src/Core/AutodocConnector.Application/Features/AutodocRestApi/AutodocLogin/AutodocLoginCommandHandler.cs
>  namespace AutodocConnector.Application.Features.AutodocRestApi.AutodocLogin
use file scoped namespaces, please!

2024-09-16 15:11 UTC, ggeryx commented on src/Core/AutodocConnector.Application/Features/AutodocRestApi/AutodocLogin/AutodocLoginCommandHandler.cs
>  namespace AutodocConnector.Application.Features.AutodocRestApi.AutodocLogin
I changed them to file scoped

2024-09-16 15:24 UTC, zgorcsos approved these changes

2024-09-16 17:08 UTC, merged